export const data = {
  firstName: {
    id: "firstName",
    lable: "First Name",
    type: "text",
    placeholder: "Enter firstName...",
    value: "",
    isError: "",
    errorMsg: "",
  },
  lastName: {
    id: "lastName",
    lable: "Last Name",
    type: "text",
    placeholder: "Enter lastName...",
    value: "",
    isError: "",
    errorMsg: "",
  },
  email: {
    id: "email",
    lable: "Email",
    type: "email",
    placeholder: "Enter email...",
    value: "",
    isError: "",
    errorMsg: "",
  },
  password: {
    id: "password",
    lable: "Password",
    type: "text",
    placeholder: "Enter password...",
    value: "",
    isError: "",
    errorMsg: "",
  },
  confirmPassword: {
    id: "confirmPassword",
    lable: "Confirm Password",
    type: "text",
    placeholder: "Enter confirmPassword...",
    value: "",
    isError: "",
    errorMsg: "",
  },
};
